### ISSUE TITLE
Icon in high resolution

### ISSUE THREAD

**Issue by stephaniebamerico** [jalvesaq/gconjugue#2]
I noticed that the application icon is in low resolution. We would like to include the application in our educational system (_Linux Educacional 6_), so we created an icon in high resolution (please see the pull request #3).

![gconjugue](https://user-images.githubusercontent.com/16976543/27864150-c192d708-6163-11e7-9c7b-723ceb5a31b4.png)

**Comment by jalvesaq** [comment]
Should I release a new version with the new icon?

**Comment by stephaniebamerico** [comment]
Thank you! We would like the package in the default repository to have the icon in high resolution as this will make it easier to include in the system. Can you tell me how long it will take for this?

**Comment by jalvesaq** [comment]
It is released now: https://github.com/jalvesaq/gconjugue/releases

**Comment by stephaniebamerico** [comment]
We would like to make the application available in _Linux Educacional 6_ in the coming weeks and we need the new version to be in the official Ubuntu repository (that is can be installed via apt). For this, you need to submit the new version of the package to the official Ubuntu repository. Do you intend to do this?

**Comment by jalvesaq** [comment]
I have only rudimentary knowledge of Debian package system, and I hope that Eriberto Mota will update the package soon. And note that packages are updated in Ubuntu only twice a year. Please, see: https://wiki.ubuntu.com/ArtfulAardvark/ReleaseSchedule
